# Generated by Django 3.2.21 on 2023-10-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('short_name', models.CharField(max_length=256, verbose_name='Shortname')),
                ('post_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('bank_account', models.TextField(blank=True, null=True, verbose_name='Account')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Developments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=128, verbose_name='Cod')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('parent', models.CharField(blank=True, max_length=128, null=True)),
                ('levels', models.CharField(blank=True, max_length=128, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=256, verbose_name='Lastname')),
                ('post_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('bank_account', models.TextField(blank=True, null=True, verbose_name='Account')),
                ('begin_work', models.DateTimeField()),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('deleted', models.BooleanField(default=False)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.developments')),
            ],
        ),
    ]
